<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[11]=array(0,1,1,'6aG66L6w566A5LuL');
$cfg_Cs[12]=array(0,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[4]=array(0,1,1,'5YWs5Y+46I2j6KqJ');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[13]=array(6,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[14]=array(6,1,1,'5oqA5pyv5paw6Ze7');
$cfg_Cs[15]=array(6,1,1,'6KGM5Lia5paw6Ze7');
?>