<?php
$z[0]=Array("arcurl","",239,254);
$z[1]=Array("title","",274,288);
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='img-responsive'><img src='{@me['litpic']}'/></a>\"); ",410,571);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",648,663);
$z[4]=Array("description","",669,689);
$z[5]=Array("pubdate","",1011,1057);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("arcurl","",1151,1166);

?>